### ISSUE TITLE
Are prototypes shared?

### ISSUE THREAD

**Issue by surma** [GoogleChrome/tasklets#4]
@drufball @bfgeek 

Question from @paullewis:

```js
// tasklet.js
export doStuff(x) {
  console.log(x.aThing); // prints `lol`
  console.log(x.anotherThing); // ???
}
```

```js
// main.js
function MyObj() { 
  this.aThing = 'lol';
}
MyObj.prototype.anotherThing = 'kek';
const obj = new MyObj()
console.log(obj.aThing); // prints `lol`
console.log(obj.anotherThing); // prints `kek`

const api = await tasklet.addModule('tasklet.js');
api.doStuff(obj);
```

Will this work?

### My take:

This would inconsistent with other APIs like `postMessage` or IndexDB, but since this API is about convenience, it’s at least worth talking about. Once you define functions on the prototype, it would break clone-ability once you define functions on the prototype, so I am worried about causing more confusion when used with classes.

Maybe more for a user-land library?

However: We should keep in mind that people are gonna straight to the vDOM use-case stuff. Most vDOM implementations use the prototype chain. So we should maybe write a mock-up of the DOM-in-Tasklet library we’ve been theorizing about.

**Comment by domenic** [comment]
Sharing prototypes would require inventing a new mechanism apart from structured serialization. I don't recommend that; that sounds like a lot of spec and implementation work, whereas the current spec just reuses existing infrastructure and is consistent with the rest of the platform.

**Comment by surma** [comment]
Thanks for the input. I’ll close this for now as it’s not worth the effort.
